
const Image = {
  HeroImage: "assets/hero-img.webp",
};

export default Image;

export const listTools = [
  {
    id: 1,
    nama: "Visual Studio Code",
    src: "assets/tools/vscode.png",
    ket: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
    nama: "React JS",
    src: "assets/tools/reactjs.png",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 3,
    nama: "Next JS",
    src: "assets/tools/nextjs.png",
    ket: "Framework",
    dad: "300",
  },
  {
    id: 4,
    nama: "Tailwind CSS",
    src: "assets/tools/tailwind.png",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    nama: "Bootstrap",
    src: "assets/tools/bootstrap.png",
    ket: "Framework",
    dad: "500",
  },
  {
    id: 6,
    nama: "Javascript",
    src: "assets/tools/js.png",
    ket: "Language",
    dad: "600",
  },
  {
    id: 7,
    nama: "Node JS",
    src: "assets/tools/nodejs.png",
    ket: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
    nama: "PHP",
    src: "assets/tools/php.png",
    ket: "Language Server-side",
    dad: "800",
  },
  {
    id: 9,
    nama: "Xampp",
    src: "assets/tools/xampp.png",
    ket: "Web Serve Localhost",
    dad: "900",
  },
  {
    id: 10,
    nama: "SQL Server",
    src: "assets/tools/sqlserver.png",
    ket: "Database Management",
    dad: "1000",
  },
  {
    id: 11,
    nama: "MySQL",
    src: "assets/tools/mysql.png",
    ket: "Database Management",
    dad: "1100",
  },
   {
    id: 12,
    nama: "Github",
    src: "assets/tools/github.png",
    ket: "Repository",
    dad: "1200",
  },
  {
    id: 13,
    nama: "Adobe Illustrator",
    src: "assets/tools/ai.png",
    ket: "Design App",
    dad: "1300",
  },
];

export const listProyek = [
  {
    id: 1,
    gambar: Proyek1,
    nama: "Website Sekolah",
    image: "assets/proyek/proyek1.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["HTML", "CSS", "Javascript", "AOS"],
    dad: "200",
  },
  {
    id: 2,
    gambar: Proyek2,
    nama: "Company Profile",
    image: "assets/proyek/proyek2.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["HTML", "CSS", "Javascript", "AOS", "Swiper", "Lightbox Gallery"],
    dad: "300",
  },
  {
    id: 3,
    gambar: Proyek3,
    nama: "Web Pernikahan 2.0",
    image: "assets/proyek/proyek3.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["Vite", "ReactJS", "TailwindCSS", "AOS"],
    dad: "400",
  },
  {
    id: 4,
    gambar: Proyek4,
    nama: "Website Course",
    image: "assets/proyek/proyek4.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["Vite", "ReactJS", "Bootstrap", "AOS"],
    dad: "500",
  },
  {
    id: 5,
    gambar: Proyek5,
    nama: "Web Portfolio",
    image: "assets/proyek/proyek5.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["HTML", "CSS", "Javascript", "Bootsrap"],
    dad: "600",
  },
  {
    id: 6,
    gambar: Proyek6,
    nama: "Company Profile 2.0",
    image: "assets/proyek/proyek6.webp",
    desk: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis, laborum!",
    tools: ["NextJS", "TailwindCSS", "Framermotion"],
    dad: "700",
  },
];
